### ISSUE TITLE
Font warnings after Typst update 0.12

### ISSUE THREAD

**Issue by cyc-987** [memset0/ZJU-Project-Report-Template#2]
Typst has reported a list of warnings with regard to font issues as the picture shows below.
<img width="684" alt="image" src="https://github.com/user-attachments/assets/f3492ba6-7443-45dc-b66c-4a35a45b4860">

**Comment by memset0** [comment]
因为这里使用的是自动 fallback 的字体方案，一般来说，他会自动匹配第一个存在的字体样式。这里的字体 fallback 列表是参考 https://zenozeng.github.io/fonts.css/ 项目给出的。如果您不想看到 warning，可以在列表中删去没有的中文字体；或者是自行上传缺失的字体文件（参考官方文档）
